{% set name = "gridtest" %}
{% set version = "0.0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6cf2215b0bbd6cbe42b55ce9ced8d0ff28b379ba340473e93597eb95e41c82ed

build:
  number: 1
  noarch: python
  entry_points:
    - gridtest=gridtest.client:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pytest-runner
  run:
    - python >={{ python_min }}
    - pyaml
    - json_tricks

test:
  requires:
    - python {{ python_min }}
  imports:
    - gridtest
    - gridtest.decorators
    - gridtest.func
    - gridtest.defaults
    - gridtest.templates
    - gridtest.utils
    - gridtest.version
    - gridtest.client
    - gridtest.client.check
    - gridtest.client.test
    - gridtest.client.update
    - gridtest.client.shell
    - gridtest.client.generate
    - gridtest.client.gridview
    - gridtest.main
    - gridtest.main.check
    - gridtest.main.generate
    - gridtest.main.grids
    - gridtest.main.helpers
    - gridtest.main.substitute
    - gridtest.main.test
    - gridtest.main.update
    - gridtest.main.workers
    - gridtest.logger
    - gridtest.logger.message
    - gridtest.logger.namer
    - gridtest.logger.progress
    - gridtest.logger.spinner
  commands:
    - gridtest --help


about:
  home: https://github.com/vsoch/gridtest
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: generate grid testing for Python modules and functions
  description: |
    GridTest is a small python library that will read in one or more python
    scripts or modules, and generate a testing file that can be used to run grid
    tests. A "gridtest" is one that is run over a grid of parameter
    settings. For each gridtest, you can also measure one or more metrics.
  doc_url: https://vsoch.github.io/gridtest
  dev_url: https://github.com/vsoch/gridtest

extra:
  recipe-maintainers:
    - vsoch
